# Classificasion Predict Student Solution

© Explore Data Science Academy

---
### Problem Statement

Many companies are built around lessening one’s environmental impact or carbon footprint. They offer products and services that are environmentally friendly and sustainable, in line with their values and ideals. They would like to determine how people perceive climate change and whether or not they believe it is a real threat. This would add to their market research efforts in gauging how their product/service may be received.

Team 8 is challenged with the task of creating a Machine Learning model that is able to classify whether or not a person believes in climate change, based on their novel tweet data. This will be achieved with the steps outlined below:

- 1. analyse the supplied data;
- 2. identify potential errors in the data and clean the existing data set;
- 3. determine if additional features can be added to enrich the data set;
- 4. build a model that is capable of forecasting the three hourly demand shortfalls;
- 5. evaluate the accuracy of the best machine learning model;
- 6. determine what features were most important in the model’s prediction decision, and
- 7. explain the inner working of the model to a non-technical audience.

Providing an accurate and robust solution to this task gives companies access to a broad base of consumer sentiment, spanning multiple demographic and geographic categories - thus increasing their insights and informing future marketing strategies.

<a id="cont"></a>

## Table of Contents

<a href=#one>1. Importing Packages</a>

<a href=#two>2. Loading Data</a>

<a href=#three>3. Exploratory Data Analysis (EDA)</a>

<a href=#four>4. Data Engineering</a>

<a href=#five>5. Modeling</a>

<a href=#six>6. Model Performance</a>

<a href=#seven>7. Model Explanations</a>

 <a id="one"></a>
## 1. Importing Packages
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Importing Packages ⚡ |
| :--------------------------- |
| In this section you are required to import, and briefly discuss, the libraries that will be used throughout your analysis and modelling. |

---

In [22]:
# Importing modules for data science and visualization
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 180 # Quality of all figures in notebook
# NLP Libraries
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.tokenize import RegexpTokenizer
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.stem import SnowballStemmer
from os import path
from PIL import Image
#from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
# ML Libraries
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk import pos_tag
#ignore warnings
import warnings
warnings.filterwarnings('ignore')

<a id="two"></a>
## 2. Loading the Data
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Loading the data ⚡ |
| :--------------------------- |
| In this section you are required to load the data from the `df_train` file into a DataFrame. |

---

In [7]:
df_train = pd.read_csv('https://github.com/Gabe-Maja/SA-Language-Identification_Classification-Hackathon/blob/main/train_set.csv?raw=true')

df_test = pd.read_csv('https://github.com/Gabe-Maja/SA-Language-Identification_Classification-Hackathon/blob/main/test_set.csv?raw=true')



<a id="three"></a>
## 3. Exploratory Data Analysis (EDA)
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Exploratory data analysis ⚡ |
| :--------------------------- |
| In this section, you are required to perform an in-depth analysis of all the variables in the DataFrame. |

---


In [17]:
df_train.head(20)

lang_id                                               text
0      xho  umgaqo-siseko wenza amalungiselelo kumaziko ax...
1      xho  i-dha iya kuba nobulumko bokubeka umsebenzi na...
2      eng  the province of kwazulu-natal department of tr...
3      nso  o netefatša gore o ba file dilo ka moka tše le...
4      ven  khomishini ya ndinganyiso ya mbeu yo ewa maana...
5      nso  dinyakišišo tše tša go dirwa gabedi ka ngwaga ...
6      tsn  kgetse nngwe le nngwe e e sa faposiwang mo tsh...
7      ven  mbadelo dze dza laelwa dzi do kwama mahatulele...
8      nso  maloko a dikhuduthamaga a ikarabela mongwe le ...
9      tsn  fa le dirisiwa lebone le tshwanetse go bontsha...
10     nbl  lapho inarha yangeqadi ingenwe ngokungasimthet...
11     ven  yo dovha hafhu ya khwaṱhisedza uri hu vhe na m...
12     zul  i-tip-offs anonymous wusizo locingo oluzimele ...
13     ssw  tekulima lokufaka ekhatsi yonkhe imisebenti ye...
14     zul  noma yiliphi ilungu lombutho wezokuvikela elin...
15     nso  c a fa tumelelo ya go hloma go aga goba go bea...
16     tso  migingiriko ya cbnrm hinkwayo yi katsa ku tumb...
17     zul  amalungu nabangabasebenzi banelungelo lokwenza...
18     sot  ka ho mengwa lefapheng la lona diprofeshenale ...
19     nbl  isitifikhethi somtjhado esingakarhunyezwa namk...

In [16]:
df_test.head(20)

index                                               text
0       1  Mmasepala, fa maemo a a kgethegileng a letlele...
1       2  Uzakwaziswa ngokufaneleko nakungafuneka eminye...
2       3         Tshivhumbeo tshi fana na ngano dza vhathu.
3       4  Kube inja nelikati betingevakala kutsi titsini...
4       5                      Winste op buitelandse valuta.
5       6  Ke feela dilense tše hlakilego, tša pono e tee...
6       7  <fn>(762010101403 AM) 1495 Final Gems Birthing...
7       8  Ntjhafatso ya konteraka ya mosebetsi: Etsa bon...
8       9  u-GEMS uhlinzeka ngezinzuzo zemithi yezifo ezi...
9      10           So, on occasion, are statistics misused.
10     11  Janewari la ngwaga ofe kapa, dikholego tša gag...
11     12  Ntirho wa mfumo : ku aka swikolo swo ringana n...
12     13  Kl.(3) e emetswe ke k. 13 ya Molaotheo Tlhabol...
13     14  Tshabo le ho se sireletsehe hoo ho ile ha baka...
14     15  Loko u nga ri na ntiyiso wa leswaku xiphiqo xa...
15     16  lokuthabatha inxaxheba kwiintshukumo neeprogra...
16     17  Icandelwana (2) lithathelwe indawo licandelo 9...
17     18  LaMatsebula Yebo Mtilankhatsa, uva kahle. Wona...
18     19  Enige persoon wat 'n bepaling van hierdie vero...
19     20                         Minisi.a' zwi amba Minisi.

In [10]:
df_train.shape

(33000, 2)

In [11]:
df_test.shape

(5682, 2)

In [12]:
# train info
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33000 entries, 0 to 32999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   lang_id  33000 non-null  object
 1   text     33000 non-null  object
dtypes: object(2)
memory usage: 515.8+ KB


In [13]:
# test info
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5682 entries, 0 to 5681
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   index   5682 non-null   int64 
 1   text    5682 non-null   object
dtypes: int64(1), object(1)
memory usage: 88.9+ KB


In [14]:
# check missing values in train dataset
df_train.isnull().sum()

lang_id    0
text       0
dtype: int64

In [15]:
# check missing values in test dataset
df_test.isnull().sum()

index    0
text     0
dtype: int64

In [135]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()


In [141]:
# Using sparse to train the model using both representations.
import scipy.sparse

# Defining the features as well as the label
X = df_train['text']
y = df_train['lang_id']  

In [39]:
# Import models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.pipeline import Pipeline
from sklearn.decomposition import LatentDirichletAllocation as LDA
from sklearn.model_selection import GridSearchCV
from sklearn import metrics

In [142]:
from sklearn.model_selection import train_test_split

# Splitting the previously defined features and label of your dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [41]:
# Creating a list of all the models to train
algs = [LogisticRegression(random_state = 5), SVC(kernel = 'linear', random_state = 5), SVC(kernel = 'rbf', random_state = 5)
        ,MultinomialNB(), KNeighborsClassifier(), DecisionTreeClassifier(max_depth=6),RandomForestClassifier()]

In [42]:
# Fitting models onto the training data and predicting.
for i in range(0, len(algs)):
    text_clf = Pipeline([('clf', algs[i])])
    ##lowercase = True,stop_words='english', ngram_range=(1, 2), analyzer='word',max_df = 0.8
    text_clf.fit(X_train, y_train)  
    predictions = text_clf.predict(X_test)
    
    
    print(algs[i])
    print(metrics.confusion_matrix(y_test,predictions))
    print(metrics.classification_report(y_test,predictions))
    print('F1_score: ',round(metrics.f1_score(y_test,predictions, average = 'weighted'),3))
    print('-------------------------------------------------------')

LogisticRegression(random_state=5)
[[580   0   0   0   0   2   0   0   0   1   0]
 [  0 615   0   0   0   0   0   0   0   0   0]
 [  0   0 576   0   0   0   0   0   0   1   6]
 [  0   0   0 622   1   0   2   0   0   0   0]
 [  0   0   0   0 618   0   0   0   0   0   0]
 [  0   0   0   0   0 583   0   0   0   0   1]
 [  1   0   0   1   3   0 592   0   1   0   0]
 [  0   0   0   0   0   0   0 561   0   0   0]
 [  0   0   0   0   0   0   0   0 634   0   0]
 [  0   0   1   0   0   0   0   0   0 602   6]
 [  0   1   8   0   0   1   0   0   0   3 577]]
              precision    recall  f1-score   support

         afr       1.00      0.99      1.00       583
         eng       1.00      1.00      1.00       615
         nbl       0.98      0.99      0.99       583
         nso       1.00      1.00      1.00       625
         sot       0.99      1.00      1.00       618
         ssw       0.99      1.00      1.00       584
         tsn       1.00      0.99      0.99       598
         tso  

In [169]:
clf = MultinomialNB(alpha=0.3)
clf.fit(vect.transform(X_train), y_train)

MultinomialNB(alpha=0.3)

In [170]:
y_pred = clf.predict(vect.transform(X_test))

In [171]:
print(metrics.classification_report(y_test, y_pred))
print('F1_score: ',round(metrics.f1_score(y_test,y_pred, average = 'weighted'),10))

              precision    recall  f1-score   support

         afr       1.00      1.00      1.00       583
         eng       1.00      1.00      1.00       615
         nbl       1.00      1.00      1.00       583
         nso       1.00      1.00      1.00       625
         sot       1.00      1.00      1.00       618
         ssw       1.00      1.00      1.00       584
         tsn       1.00      1.00      1.00       598
         tso       1.00      1.00      1.00       561
         ven       1.00      1.00      1.00       634
         xho       1.00      1.00      1.00       609
         zul       1.00      1.00      1.00       590

    accuracy                           1.00      6600
   macro avg       1.00      1.00      1.00      6600
weighted avg       1.00      1.00      1.00      6600

F1_score:  0.9993938107


## Submission to Kaggle

In [172]:
X_Kaggle = df_test['text']

In [173]:
kaggle_pred = clf.predict(vect.transform(X_Kaggle))

In [174]:
pred_df = pd.DataFrame(data=df_test['index'], columns=['index'])
pred_df.insert(1, 'lang_id', kaggle_pred, allow_duplicates=False)

pred_df.head()

index lang_id
0      1     tsn
1      2     nbl
2      3     ven
3      4     ssw
4      5     afr

In [175]:
pred_df.to_csv(path_or_buf='Gabe_MultiNB.csv', index=False)

<a id="four"></a>
## 4. Data Engineering
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Data engineering ⚡ |
| :--------------------------- |
| In this section you are required to: clean the dataset, and possibly create new features - as identified in the EDA phase. |

---

In [155]:
clf?

Type:        MultinomialNB
String form: MultinomialNB()
File:        c:\users\gabem\anaconda3\lib\site-packages\sklearn\naive_bayes.py
Docstring:  
Naive Bayes classifier for multinomial models

The multinomial Naive Bayes classifier is suitable for classification with
discrete features (e.g., word counts for text classification). The
multinomial distribution normally requires integer feature counts. However,
in practice, fractional counts such as tf-idf may also work.

Read more in the :ref:`User Guide <multinomial_naive_bayes>`.

Parameters
----------
alpha : float, default=1.0
    Additive (Laplace/Lidstone) smoothing parameter
    (0 for no smoothing).

fit_prior : bool, default=True
    Whether to learn class prior probabilities or not.
    If false, a uniform prior will be used.

class_prior : array-like of shape (n_classes,), default=None
    Prior probabilities of the classes. If specified the priors are not
    adjusted according to the data.

Attributes
----------
class_count

In [ ]:
# create new features

In [ ]:
# engineer existing features

<a id="five"></a>
## 5. Modelling
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Modelling ⚡ |
| :--------------------------- |
| In this section, you are required to create one or more regression models that are able to accurately predict the thee hour load shortfall. |

---

In [ ]:
# split data

In [ ]:
# create targets and features dataset

In [ ]:
# create one or more ML models

In [ ]:
# evaluate one or more ML models

<a id="six"></a>
## 6. Model Performance
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Model performance ⚡ |
| :--------------------------- |
| In this section you are required to compare the relative performance of the various trained ML models on a holdout dataset and comment on what model is the best and why. |

---

In [ ]:
# Compare model performance